In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import torch
print(torch.cuda.is_available())# Burda sadece GPU isleyirmi Islemirmi yoxlamaq ucun vermisem

True

In [53]:
import kagglehub

df = kagglehub.dataset_download("paramaggarwal/fashion-product-images-small")

print("Path to dataset files:", df)# kaggle- dan dataseti yukleyirem

Downloading to /root/.cache/kagglehub/datasets/paramaggarwal/fashion-product-images-small/1.archive...

100%|██████████| 565M/565M [00:36<00:00, 16.4MB/s]

Extracting files...

Path to dataset files: /root/.cache/kagglehub/datasets/paramaggarwal/fashion-product-images-small/versions/1

In [54]:
df

'/root/.cache/kagglehub/datasets/paramaggarwal/fashion-product-images-small/versions/1'

In [55]:
import os

download_path = df
csv_file_path = os.path.join(download_path, 'styles.csv')
df = pd.read_csv(csv_file_path, on_bad_lines='skip')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44424 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  44424 non-null  int64
 1   gender              44424 non-null  object
 2   masterCategory      44424 non-null  object
 3   subCategory         44424 non-null  object
 4   articleType         44424 non-null  object
 5   baseColour          44409 non-null  object
 6   season              44403 non-null  object
 7   year                44423 non-null  float64
 8   usage               44107 non-null  object
 9   productDisplayName  44417 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 3.4+ MB

In [56]:
df['image_id'] = df['id']

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44424 entries, 0 to 44423
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  44424 non-null  int64
 1   gender              44424 non-null  object
 2   masterCategory      44424 non-null  object
 3   subCategory         44424 non-null  object
 4   articleType         44424 non-null  object
 5   baseColour          44409 non-null  object
 6   season              44403 non-null  object
 7   year                44423 non-null  float64
 8   usage               44107 non-null  object
 9   productDisplayName  44417 non-null  object
 10  image_id            44424 non-null  int64
dtypes: float64(1), int64(2), object(8)
memory usage: 3.7+ MB

In [58]:
df = df.drop('id',axis=1)

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44424 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44424 non-null  object
 1   masterCategory      44424 non-null  object
 2   subCategory         44424 non-null  object
 3   articleType         44424 non-null  object
 4   baseColour          44409 non-null  object
 5   season              44403 non-null  object
 6   year                44423 non-null  float64
 7   usage               44107 non-null  object
 8   productDisplayName  44417 non-null  object
 9   image_id            44424 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.4+ MB

In [60]:
df['gender'].value_counts()# Bu hisselerde null deyerlerin temizlenmesine vaxt ayiriram

gender
Men       22147
Women     18631
Unisex     2161
Boys        830
Girls       655
Name: count, dtype: int64

In [61]:
df['masterCategory'].value_counts()

masterCategory
Apparel           21397
Accessories       11274
Footwear           9219
Personal Care      2403
Free Items          105
Sporting Goods       25
Home                  1
Name: count, dtype: int64

In [62]:
df['subCategory'].unique()

array(['Topwear', 'Bottomwear', 'Watches', 'Socks', 'Shoes', 'Belts',
       'Flip Flops', 'Bags', 'Innerwear', 'Sandal', 'Shoe Accessories',
       'Fragrance', 'Jewellery', 'Lips', 'Saree', 'Eyewear', 'Nails',
       'Scarves', 'Dress', 'Loungewear and Nightwear', 'Wallets',
       'Apparel Set', 'Headwear', 'Mufflers', 'Skin Care', 'Makeup',
       'Free Gifts', 'Ties', 'Accessories', 'Skin', 'Beauty Accessories',
       'Water Bottle', 'Eyes', 'Bath and Body', 'Gloves',
       'Sports Accessories', 'Cufflinks', 'Sports Equipment', 'Stoles',
       'Hair', 'Perfumes', 'Home Furnishing', 'Umbrellas', 'Wristbands',
       'Vouchers'], dtype=object)

In [63]:
df['articleType'].value_counts()

articleType
Tshirts                7067
Shirts                 3217
Casual Shoes           2845
Watches                2542
Sports Shoes           2036
                       ...
Cushion Covers            1
Mens Grooming Kit         1
Body Wash and Scrub       1
Suits                     1
Ipad                      1
Name: count, Length: 143, dtype: int64

In [64]:
threshold = 100

counts = df['articleType'].value_counts()
rare_classes = counts[counts < threshold].index

df['articleType'] = df['articleType'].replace(rare_classes, 'Other')

In [65]:
df['articleType'].value_counts()

articleType
Tshirts                  7067
Shirts                   3217
Casual Shoes             2845
Watches                  2542
Other                    2270
Sports Shoes             2036
Kurtas                   1844
Tops                     1762
Handbags                 1759
Heels                    1323
Sunglasses               1073
Wallets                   936
Flip Flops                914
Sandals                   897
Briefs                    849
Belts                     813
Backpacks                 724
Socks                     686
Formal Shoes              637
Perfume and Body Mist     613
Jeans                     609
Shorts                    547
Trousers                  530
Flats                     500
Bra                       477
Dresses                   464
Sarees                    427
Earrings                  416
Deodorant                 347
Nail Polish               329
Lipstick                  315
Track Pants               304
Clutches                  290
Sweatshirts               285
Caps                      283
Sweaters                  277
Ties                      263
Jackets                   258
Innerwear Vests           242
Kurtis                    234
Tunics                    229
Nightdress                189
Leggings                  177
Pendant                   176
Capris                    175
Necklace and Chains       160
Lip Gloss                 144
Night suits               141
Trunk                     140
Skirts                    128
Scarves                   119
Ring                      118
Dupatta                   116
Cufflinks                 106
Kajal and Eyeliner        102
Name: count, dtype: int64

In [66]:
df['baseColour'].value_counts()

baseColour
Black                9728
White                5538
Blue                 4918
Brown                3494
Grey                 2741
Red                  2455
Green                2115
Pink                 1860
Navy Blue            1789
Purple               1640
Silver               1090
Yellow                778
Beige                 749
Gold                  628
Maroon                581
Orange                530
Olive                 410
Multi                 394
Cream                 390
Steel                 315
Charcoal              228
Peach                 195
Off White             182
Skin                  179
Lavender              162
Grey Melange          146
Khaki                 139
Magenta               129
Teal                  120
Tan                   114
Mustard                97
Bronze                 95
Copper                 86
Turquoise Blue         69
Rust                   66
Burgundy               45
Metallic               43
Coffee Brown           31
Mauve                  29
Rose                   28
Nude                   23
Sea Green              22
Mushroom Brown         16
Taupe                  11
Lime Green              6
Fluorescent Green       5
Name: count, dtype: int64

In [67]:
threshold = 100

counts = df['baseColour'].value_counts()
rare_classes = counts[counts <= threshold].index

df['baseColour'] = df['baseColour'].replace(rare_classes, 'Other')

In [68]:
df['baseColour'].value_counts()

baseColour
Black           9728
White           5538
Blue            4918
Brown           3494
Grey            2741
Red             2455
Green           2115
Pink            1860
Navy Blue       1789
Purple          1640
Silver          1090
Yellow           778
Beige            749
Other            672
Gold             628
Maroon           581
Orange           530
Olive            410
Multi            394
Cream            390
Steel            315
Charcoal         228
Peach            195
Off White        182
Skin             179
Lavender         162
Grey Melange     146
Khaki            139
Magenta          129
Teal             120
Tan              114
Name: count, dtype: int64

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44424 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44424 non-null  object
 1   masterCategory      44424 non-null  object
 2   subCategory         44424 non-null  object
 3   articleType         44424 non-null  object
 4   baseColour          44409 non-null  object
 5   season              44403 non-null  object
 6   year                44423 non-null  float64
 7   usage               44107 non-null  object
 8   productDisplayName  44417 non-null  object
 9   image_id            44424 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.4+ MB

In [70]:
df[df['baseColour'].isnull() == True]

,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image_id
6206,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Blue Texas Jeans,11293
9516,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Black Texas Jeans,41347
12763,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Blue Texas Jeans,11288
14291,Women,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,NaN,30991
15526,Women,Personal Care,Skin,Other,NaN,Spring,2017.0,Casual,Lotus Herbals Quincenourish Quince Seed Nouris...,57698
15708,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Blue Millard Jeans,41355
17268,Men,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,GUESS Man Eau De Toilette 75 ml,43122
17639,Men,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,NaN,45687
20209,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Blue Floyd Jeans,11309
23484,Women,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,NaN,45698
34553,Men,Apparel,Bottomwear,Jeans,NaN,Fall,2016.0,Casual,Wrangler Men Blue Millard Jeans,41357
37531,Men,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,NaN,30992
40675,Men,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,NaN,43119
43260,Women,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,GUESS Seductive Women EDT Spray,43116
44224,Men,Personal Care,Fragrance,Perfume and Body Mist,NaN,Spring,2017.0,NaN,GUESS by Marciano Men Eau De Toilette 50 ml,43120

In [71]:
df = df.drop(labels = [6206,9516,12763,14291,15526,15708,17268,17639,20209,23484,34553,37531,40675,43260,44224])

In [72]:
df.tail()

,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image_id
44419,Men,Footwear,Shoes,Casual Shoes,White,Summer,2013.0,Casual,Gas Men Caddy Casual Shoe,17036
44420,Men,Footwear,Flip Flops,Flip Flops,Red,Summer,2011.0,Casual,Lotto Men's Soccer Track Flip Flop,6461
44421,Men,Apparel,Topwear,Tshirts,Blue,Fall,2011.0,Casual,Puma Men Graphic Stellar Blue Tshirt,18842
44422,Women,Personal Care,Fragrance,Perfume and Body Mist,Blue,Spring,2017.0,Casual,Rasasi Women Blue Lady Perfume,46694
44423,Women,Accessories,Watches,Watches,Pink,Winter,2016.0,Casual,Fossil Women Pink Dial Chronograph Watch ES3050,51623

In [73]:
df['baseColour'].isnull().sum()

np.int64(0)

In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44409 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44409 non-null  object
 1   masterCategory      44409 non-null  object
 2   subCategory         44409 non-null  object
 3   articleType         44409 non-null  object
 4   baseColour          44409 non-null  object
 5   season              44388 non-null  object
 6   year                44408 non-null  float64
 7   usage               44100 non-null  object
 8   productDisplayName  44407 non-null  object
 9   image_id            44409 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.7+ MB

In [75]:
df[df['season'].isnull() == True]

,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image_id
282,Women,Footwear,Shoes,Sports Shoes,Purple,NaN,2011.0,Sports,Kalenji Ekiden 200 Wn Purple 2011,5402
5997,Unisex,Footwear,Shoes,Sports Shoes,Yellow,NaN,2011.0,Sports,Kalenji Kapteren 200 Yellow Fw,5389
6510,Women,Footwear,Shoes,Sports Shoes,Purple,NaN,2011.0,Sports,Quechua Forclaz 100 Lady Purple,5380
12658,Unisex,Footwear,Shoes,Sports Shoes,White,NaN,2011.0,Sports,Kalenji Crossport 100 Whi/champ,5392
12994,Men,Footwear,Shoes,Sports Shoes,Black,NaN,2011.0,Sports,Kipsta F300 Fg Sr Ah09,5361
13523,Men,Footwear,Shoes,Sports Shoes,Red,NaN,2011.0,Sports,Kalenji Kiprun 1000 White Red Ss10,5368
16042,Women,Footwear,Shoes,Sports Shoes,Grey,NaN,2011.0,Sports,Kalenji Kapteren 100 Blue/grey,5360
21272,Men,Apparel,Topwear,Tshirts,Blue,NaN,NaN,Sports,Puma Men Blue Sless Round Neck T-shirt,53781
23835,Women,Footwear,Shoes,Sports Shoes,Blue,NaN,2011.0,Sports,Kalenji Ekiden Blue Scratch 2011,5406
24198,Women,Footwear,Shoes,Sports Shoes,Blue,NaN,2011.0,Sports,Kalenji Ekiden 100 Lady Blue 2011,5401
27725,Women,Footwear,Shoes,Sports Shoes,Beige,NaN,2011.0,Sports,Quechua Forclaz 500 L Beige Cn,5407
30113,Men,Footwear,Shoes,Sports Shoes,Black,NaN,2011.0,Sports,Inesis Canaveral 700 Black,5370
30445,Unisex,Footwear,Shoes,Sports Shoes,Black,NaN,2011.0,Sports,Btwin Road Shoes 5,5377
32246,Unisex,Footwear,Shoes,Sports Shoes,Black,NaN,2011.0,Sports,Btwin Mtb Shoes 7,5376
32615,Women,Footwear,Shoes,Sports Shoes,Blue,NaN,2011.0,Sports,Quechua Arpenaz Flex Lady Grey,5385
33691,Unisex,Footwear,Shoes,Sports Shoes,Green,NaN,2011.0,Sports,Solognac Shoes Namib 200,5365
33852,Men,Footwear,Shoes,Sports Shoes,Blue,NaN,2011.0,Sports,Kalenji Kiprun 2000 Blue Ah10,5391
34357,Men,Footwear,Shoes,Sports Shoes,Grey,NaN,2011.0,Sports,Quechua Arpenaz Flex Novadry Grey,5398
34519,Men,Footwear,Shoes,Sports Shoes,Grey,NaN,2011.0,Sports,Kalenji Ekiden 50 Wht/grey 09,5354
36121,Men,Footwear,Shoes,Sports Shoes,Grey,NaN,2011.0,Sports,Kalenji Kapteren 100 Grey/white,5355
36874,Unisex,Footwear,Shoes,Sports Shoes,Grey,NaN,2011.0,Sports,Kalenji Kapteren 100 Grey Orang,5390

In [76]:
df = df.dropna(subset=['season'])

In [77]:
df['season'].isnull().sum()

np.int64(0)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44388 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44388 non-null  object
 1   masterCategory      44388 non-null  object
 2   subCategory         44388 non-null  object
 3   articleType         44388 non-null  object
 4   baseColour          44388 non-null  object
 5   season              44388 non-null  object
 6   year                44388 non-null  float64
 7   usage               44079 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44388 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.7+ MB

In [79]:
df['usage'].value_counts()

usage
Casual          34399
Sports           4004
Ethnic           3208
Formal           2345
Smart Casual       67
Party              29
Travel             26
Home                1
Name: count, dtype: int64

In [80]:
df['usage'] = df['usage'].fillna('Casual')

In [81]:
df['usage'].value_counts()

usage
Casual          34708
Sports           4004
Ethnic           3208
Formal           2345
Smart Casual       67
Party              29
Travel             26
Home                1
Name: count, dtype: int64

In [82]:
df['usage'].isnull().sum()

np.int64(0)

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44388 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44388 non-null  object
 1   masterCategory      44388 non-null  object
 2   subCategory         44388 non-null  object
 3   articleType         44388 non-null  object
 4   baseColour          44388 non-null  object
 5   season              44388 non-null  object
 6   year                44388 non-null  float64
 7   usage               44388 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44388 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.7+ MB

In [84]:
df[df['productDisplayName'].isnull() == True]

,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,image_id
3677,Women,Accessories,Bags,Clutches,Maroon,Summer,2012.0,Casual,NaN,42878
22089,Women,Accessories,Bags,Clutches,Brown,Summer,2012.0,Casual,NaN,42863

In [85]:
df = df.drop(labels = [3677,22089])

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44386 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44386 non-null  object
 1   masterCategory      44386 non-null  object
 2   subCategory         44386 non-null  object
 3   articleType         44386 non-null  object
 4   baseColour          44386 non-null  object
 5   season              44386 non-null  object
 6   year                44386 non-null  float64
 7   usage               44386 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44386 non-null  int64
dtypes: float64(1), int64(1), object(8)
memory usage: 3.7+ MB

In [87]:
categorical = ['gender','masterCategory','subCategory','articleType','baseColour','season','usage','productDisplayName']

In [88]:
from sklearn.preprocessing import LabelEncoder
threshold = 100

counts = df['subCategory'].value_counts()
rare_classes = counts[counts <= threshold].index

df['subCategory'] = df['subCategory'].replace(rare_classes, 'Other')
le = LabelEncoder()
df['articleType'] = le.fit_transform(df['articleType'])

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44386 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44386 non-null  object
 1   masterCategory      44386 non-null  object
 2   subCategory         44386 non-null  object
 3   articleType         44386 non-null  int64
 4   baseColour          44386 non-null  object
 5   season              44386 non-null  object
 6   year                44386 non-null  float64
 7   usage               44386 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44386 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 3.7+ MB

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44386 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44386 non-null  object
 1   masterCategory      44386 non-null  object
 2   subCategory         44386 non-null  object
 3   articleType         44386 non-null  int64
 4   baseColour          44386 non-null  object
 5   season              44386 non-null  object
 6   year                44386 non-null  float64
 7   usage               44386 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44386 non-null  int64
dtypes: float64(1), int64(2), object(7)
memory usage: 3.7+ MB

In [91]:
df['season'] = le.fit_transform(df['season'])

In [92]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44386 entries, 0 to 44423
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              44386 non-null  object
 1   masterCategory      44386 non-null  object
 2   subCategory         44386 non-null  object
 3   articleType         44386 non-null  int64
 4   baseColour          44386 non-null  object
 5   season              44386 non-null  int64
 6   year                44386 non-null  float64
 7   usage               44386 non-null  object
 8   productDisplayName  44386 non-null  object
 9   image_id            44386 non-null  int64
dtypes: float64(1), int64(3), object(6)
memory usage: 3.7+ MB

In [93]:
import torch
from torch.utils.data import Dataset# Oz datasetimi yaratmaq ucun istifade edilir
from PIL import Image# Sekilleri acmaq ucun istifade edilir
import os # Fayl yollari ile islemek ucun istifade edilir
import pandas as pd
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")#Burda texti integere cevirmek ucun istifade edirem
from sklearn.preprocessing import LabelEncoder # Burda SubCategoriyinin LabelEncoding edilmis hissesini Label adli sutunu menimsedirem
le = LabelEncoder()
df['label'] = le.fit_transform(df['masterCategory'])
counts = df['label'].value_counts()
df = df[df['label'].isin(counts[counts >= 100].index)]
df['label'] = df['label'].astype('category').cat.codes


image_dir = os.path.join(download_path, 'images')#Sekillerin oldugu directory-in pathini alir

class ProductDataset(Dataset):
    def __init__(self, df, tokenizer, transform=None):#dataseti yaratmaq ucun lazimli parametrleri elave edirem
        self.df = df.reset_index(drop=True)#indexleri sifirlayir
        self.tokenizer = tokenizer
        self.transform = transform

    def __len__(self):
        return len(self.df)# nece sample oldugunu gostermek ucun veririk

    def load_image(self, img_id):# sekili diskden oxumaq ucun funksiya veririk
        path = os.path.join(image_dir, f"{img_id}.jpg") #image pathleri duzeldir

        if not os.path.exists(path):
            return None

        try:
            return Image.open(path).convert("RGB")
        except:
            return None

    def __getitem__(self, idx):
        row = self.df.iloc[idx]#bu hissede sekli goturur eger sekil uygun deyilse dummy image yaradir


        image = self.load_image(row['image_id'])


        if image is None:
            image = Image.new("RGB", (224, 224))  # dummy image

        if self.transform:
            image = self.transform(image)


        text = str(row.get('productDisplayName', ""))#textleri yaradir

        text_enc = self.tokenizer(
            text, #text  rəqəmlərə çevrilir
            padding='max_length',#padding  hamısını eyni uzunluq edir
            truncation=True,#truncation  uzun texti kəsir
            max_length=64,#max_length=64 → maksimum 64 token
            return_tensors='pt'
        )


        label = torch.tensor(row['label'], dtype=torch.long)# burda category integer olur ve tensoR formatina salinir

        return {
            "image": image,#şəkil tensor
            "input_ids": text_enc['input_ids'].squeeze(0),#text rəqəm formatı
            "attention_mask": text_enc['attention_mask'].squeeze(0),#hansı tokenlər realdır
            "label": label # burda da targetler gosterilir
        }

In [94]:
from torchvision import transforms
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])# burda sekli uygun olcuye salir ve tensor edir

In [95]:
from torch.utils.data import DataLoader
dataset = ProductDataset(df, tokenizer, transform)# burda raw data
loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=2,
    pin_memory=True
)

In [96]:
import torch
import torch.nn as nn
from transformers import DistilBertModel
from torchvision import models

class MultiModalModel(nn.Module):
    def __init__(self, num_classes):
        super().__init__()

        #TEXT MODEL (DistilBERT)
        self.text_model = DistilBertModel.from_pretrained("distilbert-base-uncased")

        #IMAGE MODEL (ResNet18)
        self.image_model = models.resnet18(pretrained=True)
        self.image_model.fc = nn.Identity()  # son layer silinir

        # FINAL CLASSIFIER
        self.classifier = nn.Sequential(
            nn.Linear(768 + 512, 256),  # 768 (text) + 512 (image)
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, num_classes)
        )

    def forward(self, input_ids, attention_mask, image):

        #  TEXT çıxışı
        text_output = self.text_model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        text_feat = text_output.last_hidden_state[:, 0, :]
        #(batch, 768) → CLS token

        #  IMAGE çıxışı
        image_feat = self.image_model(image)
        # (batch, 512)

        #  CONCAT
        combined = torch.cat((text_feat, image_feat), dim=1)

        # CLASSIFIER
        output = self.classifier(combined)

        return output

In [97]:
import torch
import torch.nn as nn
import numpy as np
from tqdm import tqdm
from sklearn.utils.class_weight import compute_class_weight


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = MultiModalModel(num_classes=len(df['label'].unique()))
model = model.to(device)

# CLASS WEIGHTS (ƏSAS FIX)
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(df['label']),
    y=df['label']
)

weights = torch.tensor(class_weights, dtype=torch.float).to(device)

#loss
criterion = nn.CrossEntropyLoss(weight=weights)

# optimizer
optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)

# training
for epoch in range(5):
    model.train()
    total_loss = 0

    for i, batch in enumerate(tqdm(loader)):
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        images = batch['image'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids, attention_mask, images)

        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()



    print(f"Epoch {epoch} Avg Loss: {total_loss/len(loader):.4f}")

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

DistilBertModel LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |  |
------------------------+------------+--+-
vocab_layer_norm.bias   | UNEXPECTED |  |
vocab_transform.bias    | UNEXPECTED |  |
vocab_transform.weight  | UNEXPECTED |  |
vocab_layer_norm.weight | UNEXPECTED |  |
vocab_projector.bias    | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
100%|██████████| 1387/1387 [06:00<00:00,  3.85it/s]

Epoch 0 Avg Loss: 0.2208

100%|██████████| 1387/1387 [05:58<00:00,  3.87it/s]

Epoch 1 Avg Loss: 0.1724

100%|██████████| 1387/1387 [05:58<00:00,  3.87it/s]

Epoch 2 Avg Loss: 0.1461

100%|██████████| 1387/1387 [05:58<00:00,  3.87it/s]

Epoch 3 Avg Loss: 0.1312

100%|██████████| 1387/1387 [05:58<00:00,  3.87it/s]

Epoch 4 Avg Loss: 0.1506

In [98]:
model.eval()#Modeli test/evaluation rejiminə keçirir yeni data artiq oyrenmir sadece proqnoz verir

MultiModalModel(
  (text_model): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (image_model): ResNet(
    (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (relu): ReLU(inplace=True)
    (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (layer1): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer2): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 128, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(64, 128, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer3): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(128, 256, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(128, 256, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (layer4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(256, 512, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (downsample): Sequential(
          (0): Conv2d(256, 512, kernel_size=(1, 1), stride=(2, 2), bias=False)
          (1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        )
      )
      (1): BasicBlock(
        (conv1): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(512, 512, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
    )
    (avgpool): AdaptiveAvgPool2d(output_size=(1, 1))
    (fc): Identity()
  )
  (classifier): Sequential(
    (0): Linear(in_features=1280, out_features=256, bias=True)
    (1): ReLU()
    (2): Dropout(p=0.3, inplace=False)
    (3): Linear(in_features=256, out_features=5, bias=True)
  )
)

In [99]:
all_preds = []
all_labels = []

with torch.no_grad():# burda gradient hesablanmasin deye veririk bu surete tesir edir
    for batch in loader:  #datani batch seklinde yukleyir
        input_ids = batch['input_ids'].to(device)#token-lar (DistilBERT üçün)
        attention_mask = batch['attention_mask'].to(device)#hansi tokenin real oldugunu deyir
        images = batch['image'].to(device)#CNN hissesi ucun sekiller
        labels = batch['label'].to(device)# bu da dogru cavablar

        outputs = model(input_ids, attention_mask, images)#burda datani text+image seklinde qebul edir ve cixis verir

        preds = torch.argmax(outputs, dim=1)#bu da en boyuk score-u goturur

        all_preds.extend(preds.cpu().numpy())#Gpu da olan datani cpu getirir ve numpy array seklinde geri qaytarir
        all_labels.extend(labels.cpu().numpy())# real cavablari saxlayir

In [100]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

acc = accuracy_score(all_labels, all_preds)
print("Accuracy:", acc)
print("Classification Report: \n",classification_report(all_labels, all_preds))
print('Confusion Matrix: \n',confusion_matrix(all_labels, all_preds))# Burda da metricleri predict edirik

Accuracy: 0.9877141568981064
Classification Report:
               precision    recall  f1-score   support

           0       0.99      0.98      0.98     11272
           1       1.00      0.99      0.99     21390
           2       1.00      1.00      1.00      9199
           3       0.31      0.55      0.39       105
           4       0.94      1.00      0.97      2394

    accuracy                           0.99     44360
   macro avg       0.84      0.90      0.87     44360
weighted avg       0.99      0.99      0.99     44360

Confusion Matrix:
 [[11047    77    12    90    46]
 [   89 21154     1    42   104]
 [   12    12  9169     0     6]
 [   36     5     1    58     5]
 [    5     2     0     0  2387]]